﻿// treeManager.js - 树结构管理核心模块

/**
 * 递归比较两个数组的字典序（支持嵌套数组）
 * 默认比较器，当记号系统未提供 compare 时使用
 */
export function compareArrays(a, b) {
    if (Array.isArray(a) && Array.isArray(b)) {
        const minLen = Math.min(a.length, b.length);
        for (let i = 0; i < minLen; i++) {
            const c = compareArrays(a[i], b[i]);
            if (c !== 0) return c;
        }
        return a.length - b.length;
    } else {
        if (a > b) return 1;
        if (a < b) return -1;
        return 0;
    }
}

/**
 * 树节点类
 */
export class TreeNode {
    constructor(type, data = null, parentId = null, isAutoGenerated = false, clickIndex = 0) {
        this.id = 0;
        this.type = type;                    // 'LIMIT' 或 'NORMAL'
        this.data = data;
        this.expansionCount = -1;
        this.expansionClickCount = 0;
        this.hasExpanded = false;
        this.parentId = parentId;
        this.children = [];                  // 子节点 ID 列表（按展开顺序降序）
        this.isExpanded = false;
        this.isAutoGenerated = isAutoGenerated;
        this.clickIndex = clickIndex;
        this.userInput = '';
        this.hidesSmaller = false;
        this.isSuccessor = false;
        this.error = null;
    }
}

/**
 * 树管理器
 * @param {Object} notation - 记号系统适配器
 */
export class TreeManager {
    constructor(notation) {
        this.Notation = notation;
        if (!this.Notation.compare) {
            this.Notation.compare = compareArrays;
        }
        this.nodes = new Map();
        this.root = null;
        this.nodeIdCounter = 0;
    }

    _registerNode(node) {
        node.id = ++this.nodeIdCounter;
        this.nodes.set(node.id, node);
        return node;
    }

    _updateSuccessorFlag(node) {
        const N = this.Notation;
        if (node.type === 'LIMIT') {
            node.isSuccessor = false;
            return;
        }
        if (N && typeof N.isSuccessor === 'function') {
            node.isSuccessor = N.isSuccessor(node.data);
        } else {
            node.isSuccessor = false;
        }
    }

    init(limitExpr) {
        const isLim = this.Notation.isLimit ? this.Notation.isLimit(limitExpr) : false;
        const root = new TreeNode(isLim ? 'LIMIT' : 'NORMAL', limitExpr);
        root.isExpanded = true;
        this._registerNode(root);
        this.root = root;
        this._updateSuccessorFlag(root);
        return this;
    }

    initPlaceholder() {
        const root = new TreeNode('LIMIT', null);
        root.isExpanded = true;
        this._registerNode(root);
        this.root = root;
        this._updateSuccessorFlag(root);
        return this;
    }

    getNode(id) {
        return this.nodes.get(id) || null;
    }

    getParent(nodeId) {
        const node = this.nodes.get(nodeId);
        if (!node || !node.parentId) return null;
        return this.nodes.get(node.parentId) || null;
    }

    getChildren(nodeId) {
        const node = this.nodes.get(nodeId);
        if (!node) return [];
        return node.children.map(cid => this.nodes.get(cid)).filter(Boolean);
    }

    getNextSibling(nodeId) {
        const parent = this.getParent(nodeId);
        if (!parent) return null;
        const idx = parent.children.indexOf(nodeId);
        if (idx !== -1 && idx + 1 < parent.children.length) {
            return this.nodes.get(parent.children[idx + 1]) || null;
        }
        return null;
    }

    getGlobalMaxSmaller(targetData) {
        const N = this.Notation;
        let maxData = null;
        for (const [, node] of this.nodes) {
            if (node.type === 'NORMAL') {
                if (N.compare(node.data, targetData) < 0) {
                    if (maxData === null || N.compare(node.data, maxData) > 0) {
                        maxData = node.data;
                    }
                }
            }
        }
        return maxData;
    }

    addChild(parentId, childNode) {
        const parent = this.nodes.get(parentId);
        if (!parent) return false;
        const N = this.Notation;
        if (N && typeof N.isEmpty === 'function' && N.isEmpty(childNode.data)) {
            return false;
        }
        this._registerNode(childNode);
        parent.children.unshift(childNode.id);
        this._updateSuccessorFlag(childNode);
        return true;
    }

    _getNextInPreOrder(nodeId) {
        const node = this.nodes.get(nodeId);
        if (!node) return null;

        if (node.children.length > 0) {
            const firstChildId = node.children[0];
            return this.nodes.get(firstChildId) || null;
        }

        let currentId = nodeId;
        while (currentId !== null) {
            const parent = this.getParent(currentId);
            if (!parent) return null;

            const siblings = parent.children;
            const idx = siblings.indexOf(currentId);
            if (idx !== -1 && idx + 1 < siblings.length) {
                const nextSiblingId = siblings[idx + 1];
                return this.nodes.get(nextSiblingId) || null;
            }
            currentId = parent.id;
        }
        return null;
    }

    // ==================== 修改后的 expandNode ====================
    expandNode(nodeId, options = {}) {
        const N = this.Notation;
        const node = this.nodes.get(nodeId);
        if (!node) return { success: false, message: '节点不存在' };

        if (!node.isExpanded) {
            return { success: false, message: '请先切换到展开状态' };
        }
        if (node.type === 'NORMAL' && typeof N.isEmpty === 'function' && N.isEmpty(node.data)) {
            return { success: false, message: '空表达式节点不可展开' };
        }

        node.hasExpanded = true;
        if (!node.expansionClickCount) node.expansionClickCount = 0;
        node.expansionClickCount++;
        const currentClickIndex = node.expansionClickCount;

        // 获取后继节点作为目标上限
        let successorNode = null;
        if (node.type === 'NORMAL' && N && typeof N.compare === 'function') {
            successorNode = this._getNextInPreOrder(nodeId);
            if (successorNode && successorNode.type !== 'NORMAL') {
                successorNode = null;
            }
        }

        let finalK = null;
        let finalData = null;
        const MAX_ATTEMPTS = 100;

        // ---------- 展开计算（不变） ----------
        if (successorNode) {
            const targetData = successorNode.data;
            let attempts = 0;
            while (attempts < MAX_ATTEMPTS) {
                const k = node.expansionCount + 1;
                let newData = null;
                if (node.type === 'LIMIT' && node.data === null) {
                    if (typeof N.expandLimit !== 'function') {
                        return { success: false, message: '记号系统未实现 expandLimit' };
                    }
                    newData = N.expandLimit(k);
                } else {
                    if (typeof N.expandNormal !== 'function') {
                        return { success: false, message: '记号系统未实现 expandNormal' };
                    }
                    newData = N.expandNormal(node.data, k);
                }

                if (N.isEmpty && N.isEmpty(newData)) {
                    node.expansionCount = k;
                    attempts++;
                    continue;
                }

                const cmp = N.compare(newData, targetData);
                if (cmp <= 0) {
                    node.expansionCount = k;
                    attempts++;
                    continue;
                } else {
                    finalK = k;
                    finalData = newData;
                    break;
                }
            }
            if (finalData === null) {
                return { success: false, message: '展开结果无法超过后继节点（尝试次数过多或生成失败）' };
            }
        } else {
            let attempts = 0;
            while (attempts < MAX_ATTEMPTS) {
                const k = node.expansionCount + 1;
                let newData = null;
                if (node.type === 'LIMIT' && node.data === null) {
                    if (typeof N.expandLimit !== 'function') {
                        return { success: false, message: '记号系统未实现 expandLimit' };
                    }
                    newData = N.expandLimit(k);
                } else {
                    if (typeof N.expandNormal !== 'function') {
                        return { success: false, message: '记号系统未实现 expandNormal' };
                    }
                    newData = N.expandNormal(node.data, k);
                }

                if (N.isEmpty && N.isEmpty(newData)) {
                    node.expansionCount = k;
                    attempts++;
                    continue;
                }
                finalK = k;
                finalData = newData;
                break;
            }
            if (finalData === null) {
                return { success: false, message: '展开结果为空（尝试多次后）' };
            }
        }
        // -----------------------------------------

        // ========== 插入逻辑：根据 isSuccessor 决定 ==========
        // 如果是后继节点，尝试插入到当前节点的正下方（兄弟位置）
        // 否则作为子节点添加
        let parentIdForNewNode = nodeId;       // 默认为子节点
        let insertAsSibling = false;

        if (node.isSuccessor) {
            const parent = this.getParent(nodeId);
            if (parent) {
                parentIdForNewNode = parent.id;
                insertAsSibling = true;
            }
        }

        const newNode = new TreeNode('NORMAL', finalData, parentIdForNewNode, false, currentClickIndex);

        let added = false;
        if (insertAsSibling) {
            const parent = this.getParent(nodeId);
            if (parent) {
                const idx = parent.children.indexOf(nodeId);
                if (idx !== -1) {
                    this._registerNode(newNode);
                    // 插入到当前节点之后（因为 children 是降序，idx+1 即为正下方）
                    parent.children.splice(idx + 1, 0, newNode.id);
                    this._updateSuccessorFlag(newNode);
                    added = true;
                }
            }
        }

        // 若未能作为兄弟插入（例如无父节点或插入失败），则回退为添加子节点
        if (!added) {
            if (!this.addChild(nodeId, newNode)) {
                return { success: false, message: '添加节点失败' };
            }
        }

        node.expansionCount = finalK;
        return { success: true, message: '展开成功', newNodeId: newNode.id };
    }
    // ==================== 修改结束 ====================

    toggleNode(nodeId) {
        const node = this.nodes.get(nodeId);
        if (!node) return { success: false, message: '节点不存在' };
        if (!node.hasExpanded) {
            return { success: false, message: '请先展开该节点' };
        }
        node.isExpanded = !node.isExpanded;
        return { success: true, message: node.isExpanded ? '已展开' : '已折叠', isExpanded: node.isExpanded };
    }

    getAllNodes() {
        return this.nodes;
    }

    getRoot() {
        return this.root;
    }

    _performTruncation(parentId, sourceData, clickIndex) {
        return null;
    }

    canExpandNode(nodeId) {
        const N = this.Notation;
        const node = this.nodes.get(nodeId);
        if (!node) return false;

        // ========== 已删除 isSuccessor 拦截（注释掉） ==========
        // if (node.type === 'NORMAL' && N.isSuccessor && N.isSuccessor(node.data)) return false;
        // =====================================================

        if (node.type === 'NORMAL' && typeof N.isEmpty === 'function' && N.isEmpty(node.data)) return false;

        // ========== 修复：移除 parentId 限制 ==========
        let successorNode = null;
        if (node.type === 'NORMAL' && N && typeof N.compare === 'function') {
            successorNode = this._getNextInPreOrder(nodeId);
            if (successorNode && successorNode.type !== 'NORMAL') {
                successorNode = null;
            }
        }
        // ==============================================

        let tempExpansionCount = node.expansionCount;
        let attempts = 0;
        const MAX_ATTEMPTS = 100;

        if (successorNode) {
            const targetData = successorNode.data;
            while (attempts < MAX_ATTEMPTS) {
                const k = tempExpansionCount + 1;
                let newData = null;

                if (node.type === 'LIMIT' && node.data === null) {
                    if (typeof N.expandLimit !== 'function') return false;
                    newData = N.expandLimit(k);
                } else {
                    if (typeof N.expandNormal !== 'function') return false;
                    newData = N.expandNormal(node.data, k);
                }

                if (N.isEmpty && N.isEmpty(newData)) {
                    tempExpansionCount = k;
                    attempts++;
                    continue;
                }

                const cmp = N.compare(newData, targetData);
                if (cmp > 0) {
                    return true;
                } else {
                    tempExpansionCount = k;
                    attempts++;
                    continue;
                }
            }
            return false;
        } else {
            while (attempts < MAX_ATTEMPTS) {
                const k = tempExpansionCount + 1;
                let newData = null;

                if (node.type === 'LIMIT' && node.data === null) {
                    if (typeof N.expandLimit !== 'function') return false;
                    newData = N.expandLimit(k);
                } else {
                    if (typeof N.expandNormal !== 'function') return false;
                    newData = N.expandNormal(node.data, k);
                }

                if (N.isEmpty && N.isEmpty(newData)) {
                    tempExpansionCount = k;
                    attempts++;
                    continue;
                }
                return true;
            }
            return false;
        }
    }
}